# Generated by Django 2.0.13 on 2019-03-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingscreen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtitle', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=150)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
