# Generated by Django 2.0.13 on 2019-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listingscreen', '0002_movielist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShowList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=200)),
                ('seasons', models.IntegerField()),
                ('network', models.CharField(max_length=150)),
                ('episodes', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='movielist',
            name='rating',
            field=models.FloatField(),
        ),
    ]
